### ISSUE TITLE
Public Certificate Path and Private Key Path

### ISSUE THREAD

**Issue by yosefromano** [eileenmcnaughton/nz.co.fuzion.civixero#23]
I noticed that in your example for the Xero Public Certificate Path and the Xero Private Key Path,
you used a path of the type c:/xamp/... Can a URL be used instead?
I am using Pantheon for hosting and as far as I know, I don't have access to the server. 
Thanks in advance

**Comment by eileenmcnaughton** [comment]
I guess so - but it doesn't sound very secure to do that...

**Comment by yosefromano** [comment]
I didn't think so either...

**Comment by xurizaemon** [comment]
@yosefromano check out [Pantheon's Private Paths](https://pantheon.io/docs/private-paths/).

I believe there are also some other directories available in your Pantheon hosting which are outside the webroot, but it looks like the above is what you're seeking.

Because of the way Pantheon works, the absolute path to your files will change over time. Either reference the files relative to the CMS's `index.php` or (I think) look into the environment variables Pantheon makes available to give you the current location of your webroot.

**Comment by eileenmcnaughton** [comment]
I think the new 2.0 release means this has changed anyway
