### ISSUE TITLE
Sync is not working 

### ISSUE THREAD

**Issue by anushkanz** [eileenmcnaughton/nz.co.fuzion.civixero#52]
Hi i manage to setup everything as this description mentioned, But I am not able to Sync my contact with Xero and CiviCRM on WP, 
I am looking for
![Screen Shot 2019-06-24 at 1 16 01 PM](https://user-images.githubusercontent.com/8416639/59984988-b1897000-9682-11e9-8206-e2dfebcf14db.png)
![Screen Shot 2019-06-24 at 1 16 31 PM](https://user-images.githubusercontent.com/8416639/59984989-b2220680-9682-11e9-80d8-9f17794d7019.png)

 any idea about this matter
Thanks

**Comment by eileenmcnaughton** [comment]
So assuming your credentials are configured correctly the synchronization happens when various apis are run - usually via a scheduled job. If you already have contacts in Xero it's usually a good idea to pull them back & do some matching as a first step.

There should be some jobs visible in the scheduled jobs. If you add a contribution then that contact and the contribution will be added to the civicrm_account_contact & civicrm_account_contribution (I think) tables to be pushed up. If you have rows in those then ideally you would try running the contact.push job first - I believe this will be visible on your scheduled jobs page. If there are errors the you will likely see them there

(this is all a lot of info & a bit jumbled but if you give more on where you are at hopefully I can help better)

**Comment by anushkanz** [comment]
Hey, Thanks for getting me back,
I already make this user both Xero, WP and Civicrm, When I try to sync its not give me any error but show no contact to match.
![Screen Shot 2019-06-27 at 10 27 05 AM](https://user-images.githubusercontent.com/8416639/60219461-927b2000-98c6-11e9-91fe-00f7ddbf3ee3.png)
![Screen Shot 2019-06-27 at 10 27 19 AM](https://user-images.githubusercontent.com/8416639/60219462-927b2000-98c6-11e9-8774-a899daa523b3.png)
![Screen Shot 2019-06-27 at 10 28 03 AM](https://user-images.githubusercontent.com/8416639/60219463-927b2000-98c6-11e9-84b3-680be089764b.png)

**Comment by eileenmcnaughton** [comment]
I've just released version 2.0 based on work done by Veda Consulting - so this will have changed...
